/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial.ManipularCadastros;

/**
 *
 * @author roger
 */
public class AdicionarNovoFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarNovoFornecedor
     */
    public AdicionarNovoFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFTFNome = new javax.swing.JFormattedTextField();
        jLNome = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLCnpj = new javax.swing.JLabel();
        jLTaxaDesconto = new javax.swing.JLabel();
        jFTFEndereco = new javax.swing.JFormattedTextField();
        jFTFCnpj = new javax.swing.JFormattedTextField();
        jFTFTaxaDesconto = new javax.swing.JFormattedTextField();

        jFTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNomeActionPerformed(evt);
            }
        });

        jLNome.setText("Nome:");

        jLEndereco.setText("Endereço:");

        jLCnpj.setText("CNPJ:");

        jLTaxaDesconto.setText("Taxa Desconto:");

        jFTFCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFCnpjActionPerformed(evt);
            }
        });

        jFTFTaxaDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFTaxaDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTaxaDesconto)
                    .addComponent(jLCnpj)
                    .addComponent(jLEndereco)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFCnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFTaxaDesconto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFTFCnpj, jFTFEndereco, jFTFNome, jFTFTaxaDesconto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco)
                    .addComponent(jFTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCnpj)
                    .addComponent(jFTFCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTaxaDesconto)
                    .addComponent(jFTFTaxaDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNomeActionPerformed

    private void jFTFCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFCnpjActionPerformed

    private void jFTFTaxaDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFTaxaDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFTaxaDescontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTFCnpj;
    private javax.swing.JFormattedTextField jFTFEndereco;
    private javax.swing.JFormattedTextField jFTFNome;
    private javax.swing.JFormattedTextField jFTFTaxaDesconto;
    private javax.swing.JLabel jLCnpj;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLTaxaDesconto;
    // End of variables declaration//GEN-END:variables
}
