/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial.ManipularCadastros;

/**
 *
 * @author roger
 */
public class AtualizarDadosCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form AtualizarDados
     */
    public AtualizarDadosCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFTFNomeAtualizado = new javax.swing.JFormattedTextField();
        jLNome = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLCpf = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jFTFEnderecoAtualizado = new javax.swing.JFormattedTextField();
        jFTFCpfAtualizado = new javax.swing.JFormattedTextField();
        jFTFTelefoneAtualizado = new javax.swing.JFormattedTextField();

        jFTFNomeAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNomeAtualizadoActionPerformed(evt);
            }
        });

        jLNome.setText("Nome:");

        jLEndereco.setText("Endereço:");

        jLCpf.setText("CPF:");

        jLTelefone.setText("Telefone:");

        jFTFCpfAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFCpfAtualizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTelefone)
                    .addComponent(jLNome)
                    .addComponent(jLEndereco)
                    .addComponent(jLCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFNomeAtualizado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFEnderecoAtualizado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFCpfAtualizado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFTelefoneAtualizado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFTFCpfAtualizado, jFTFEnderecoAtualizado, jFTFNomeAtualizado, jFTFTelefoneAtualizado});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNomeAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco)
                    .addComponent(jFTFEnderecoAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCpf)
                    .addComponent(jFTFCpfAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefone)
                    .addComponent(jFTFTelefoneAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFTFCpfAtualizado, jFTFEnderecoAtualizado, jFTFNomeAtualizado, jFTFTelefoneAtualizado, jLCpf, jLEndereco, jLNome, jLTelefone});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFNomeAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNomeAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNomeAtualizadoActionPerformed

    private void jFTFCpfAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFCpfAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFCpfAtualizadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTFCpfAtualizado;
    private javax.swing.JFormattedTextField jFTFEnderecoAtualizado;
    private javax.swing.JFormattedTextField jFTFNomeAtualizado;
    private javax.swing.JFormattedTextField jFTFTelefoneAtualizado;
    private javax.swing.JLabel jLCpf;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLTelefone;
    // End of variables declaration//GEN-END:variables
}
