/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial.ManipularCadastros;

/**
 *
 * @author roger
 */
public class AtualizarDadosFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarDadosFornecedor
     */
    public AtualizarDadosFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFTFTaxaDescontoAtualizado = new javax.swing.JFormattedTextField();
        jFTFNomeAtualizado = new javax.swing.JFormattedTextField();
        jLNome = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLCnpj = new javax.swing.JLabel();
        jLTaxaDesconto = new javax.swing.JLabel();
        jFTFEnderecoAtualizado = new javax.swing.JFormattedTextField();
        jFTFCnpjAtualizado = new javax.swing.JFormattedTextField();

        jFTFTaxaDescontoAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFTaxaDescontoAtualizadoActionPerformed(evt);
            }
        });

        jFTFNomeAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNomeAtualizadoActionPerformed(evt);
            }
        });

        jLNome.setText("Nome:");

        jLEndereco.setText("Endereço:");

        jLCnpj.setText("CNPJ:");

        jLTaxaDesconto.setText("Taxa Desconto:");

        jFTFEnderecoAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFEnderecoAtualizadoActionPerformed(evt);
            }
        });

        jFTFCnpjAtualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFCnpjAtualizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTaxaDesconto)
                    .addComponent(jLCnpj)
                    .addComponent(jLEndereco)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFNomeAtualizado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFEnderecoAtualizado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFCnpjAtualizado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFTFTaxaDescontoAtualizado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFNomeAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco)
                    .addComponent(jFTFEnderecoAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCnpj)
                    .addComponent(jFTFCnpjAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTaxaDesconto)
                    .addComponent(jFTFTaxaDescontoAtualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFTaxaDescontoAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFTaxaDescontoAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFTaxaDescontoAtualizadoActionPerformed

    private void jFTFNomeAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNomeAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNomeAtualizadoActionPerformed

    private void jFTFCnpjAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFCnpjAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFCnpjAtualizadoActionPerformed

    private void jFTFEnderecoAtualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFEnderecoAtualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFEnderecoAtualizadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTFCnpjAtualizado;
    private javax.swing.JFormattedTextField jFTFEnderecoAtualizado;
    private javax.swing.JFormattedTextField jFTFNomeAtualizado;
    private javax.swing.JFormattedTextField jFTFTaxaDescontoAtualizado;
    private javax.swing.JLabel jLCnpj;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLTaxaDesconto;
    // End of variables declaration//GEN-END:variables
}
