/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial.ManipularCadastros;

/**
 *
 * @author roger
 */
public class RemoverFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverFornecedor
     */
    public RemoverFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCpfFornecedorExcluido = new javax.swing.JLabel();
        jFTFCpfFornecedorExcluido = new javax.swing.JFormattedTextField();

        jLCpfFornecedorExcluido.setText("CNPJ do fornecedor a ser excluído:");

        jFTFCpfFornecedorExcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFCpfFornecedorExcluidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLCpfFornecedorExcluido)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFTFCpfFornecedorExcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLCpfFornecedorExcluido)
                .addGap(18, 18, 18)
                .addComponent(jFTFCpfFornecedorExcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFCpfFornecedorExcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFCpfFornecedorExcluidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFCpfFornecedorExcluidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTFCpfFornecedorExcluido;
    private javax.swing.JLabel jLCpfFornecedorExcluido;
    // End of variables declaration//GEN-END:variables
}
